on: [push, pull_request]
name: Ansible modules ganeti
jobs:
  test:
    name: "Test Ansible Modules"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to github docker repository
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Pull the ganeti fake cluster docker image
      run: docker pull docker.pkg.github.com/sipgate/ganeti-docker/image:latest
    - name: Run Docker Image
      run: |
            docker run -d -p 5080:5080 --cap-add=NET_ADMIN docker.pkg.github.com/sipgate/ganeti-docker/image:latest
    - name: Test wether RAPI is running
      run: curl localhost:5080
